### ISSUE TITLE
TypeError: msTrans.translate is not a function

### ISSUE THREAD

**Issue by BastiTee** [GovBotIO/govbot-sdk#2]
Ich experimentiere gerade mit dem GovBot SDK, komme aber an folgender Fehlermeldung nicht vorbei.

```
Debugger listening on [::]:5858
Include botPegelstandBonn on /botPegelstandBonn
GovBotSDK (V 0.1.0) listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
generated guid: 69177030-cb0d-f61e-7686-1fc5e948ea69
User language is "en-US"
(node:9351) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: msTrans.translate is not a function
```

System: Ubuntu Linux 17.10 Kernel 4.8.0-58-generic #63~16.04.1-Ubuntu
Microsoft Bot Framework Emulator Release 3.5.35 Build from source
govbot-sdk commit 5be2d6ab052

Ich habe eigentlich nur den Emulator gestartet, das SDK mit dem Pegelstandbot und erhalte die Fehlermeldung bei jedem Aufruf. Auch mit dem Standardbot, der dabei ist. Eventuell meine Plattform-Language?

**Comment by rawroland** [comment]
Was ist deine nodejs Version?

**Comment by BastiTee** [comment]
nodejs Version ist 6.11.4 
Ich habe übrigens das Locale gerade auf de_DE umgestellt und jetzt ist das PRoblem weg.
Sonst habe ich nichts geändert. Fehlermeldungen sehen so aus, als würde er versuchen, wegen en_US irgendein Translator zu starten, der nicht da ist.

**Comment by rawroland** [comment]
Der Fehler wird erzeugt, weil die Variable `MICROSOFT_BING_TRANSLATE_KEY_1` in deiner *.env* fehlt. Diese Variable wird für die Übersetzung benötigt. Eine Umstellung auf *de_DE* führt dazu, dass Nachrichten nicht mehr übersetzt werden, deshalb hat es wieder funktioniert. 

Ich werde die Doku um die Info der Umgebungsvariable erweitern.

**Comment by BastiTee** [comment]
Danke!

**Comment by BastiTee** [comment]
Hey @rawroland, wie schaut es denn hier nun mit einem Update aus? Ich habe versucht in der .env den Wert für MICROSOFT_BING_TRANSLATE_KEY_1 auf irgendwas zu setzen, aber das scheint so nicht zu klappen. Was muss denn da nun rein?

**Comment by knicken** [comment]
Hallo @BastiTee ,
du musst dir direkt bei Microsoft einen Translate Key erstellen lassen. Bis Ende März wird Microsoft alle angebotenen Services in die Azure Cloud umziehen. Daher befinden wir uns auch gerade in einer Migrationsphase, entschuldige bitte also die späten Antworten. 
Wenn du dich bei Azure angemeldet hast, findest du unter "AI + Cognitive Services" die "Translator Text API". Nach dem Erstellen findest du deine Key im Menü "Quick start": 
<img width="356" alt="bildschirmfoto 2018-03-08 um 14 10 18" src="https://user-images.githubusercontent.com/5711499/37152730-9a558dfa-22da-11e8-931d-d7f79a04c821.png">


Viele Grüße
Benedict

**Comment by BastiTee** [comment]
Hi Benedict, 
okay, dass könnte ich machen, aber es ist langfristig schon schöner, wenn man die Standardsprache angeben könnte. 
D.h. bloß weil ich jetzt auf einem en_US Rechner arbeite, will ich ja nicht, dass eine Eingabe á la "Wo ist das nächste freie Parkhaus in Bonn?" durch Microsoft Translate geroutet wird. Wenn ich es richtig sehe, passiert das ja nicht, wenn meine Platform de_DE ist, ergo ist es nicht vom Eingabetext abhängig.
Seht ihr eine einfache Möglichkeit, dass als Option anzubieten...
```
node --debug app.js --locale de_DE
```
oder
```
node --debug app.js --ignore-locale
```
?
Danke und Gruß,
Basti.

**Comment by knicken** [comment]
Hey,
ich hätte spontan zwei Ideen:
Die einfachste Option wäre im Bot Framework Emulator die Locale auf "de_DE" zu setzen.
<img width="906" alt="bildschirmfoto 2018-03-08 um 15 05 59" src="https://user-images.githubusercontent.com/5711499/37155596-f0b86060-22e3-11e8-91c1-1c5f99432698.png">
Längerfristig wäre es aber natürlich auch möglich den govBotInterceptor dahingehend anzupassen, dass die Translation optional wird. Wenn du das feature dringend benötigst, erstelle doch bitte einen feature request oder auch gleich einen pull request.
Viele Grüße
Benedict

**Comment by BastiTee** [comment]
Danke, Benedict. Deine erste Option funktioniert.
Allerdings muss das Locale "de" dort eingetragen werden, nicht "de_DE".

**Comment by BastiTee** [comment]
Nachtrag: https://github.com/GovBotIO/govbot-sdk/pull/3
