### ISSUE TITLE
Weiterführende Dokumentation

### ISSUE THREAD

**Issue by BastiTee** [GovBotIO/govbot-sdk#5]
Hallo GovBot-Team,

nachdem ich mir jetzt ähnlich dem Pegelstandbot einen eigenen, simplen Anwendungsfall für den Botty Bonn Bot gebaut habe, bin ich schnell an die Grenzen der Dokumentation gestoßen. Hier mal meine gesammelten Fragen:

- Woher kommt dieses Sessionobjekt, das mir mitgeliefert wird und welche Informationen sind relevant für mich? Zum Beispiel:
  - Allgemeine Dokumentation zu dem Objekt (das ist ja nicht Teil des SDK Sourcecode) 
  - Welches Datum ist maßgeblich, um Sessions zuzuordnen? Entspricht eine Session einem verbundenen Client?
  - Muss ich bei Mehrbenutzern die einzelnen Dialoge im Bot selbst speichern und zuordnen oder kann ich mich auf irgendein Datum in der Session verlassen? 
  - Kann ich die Session nutzen, um selber Informationen zwischen Anfragen durchzuschleifen? Wenn ja, wie? 
- Mindestens wäre eine genauere Definition des Objekts session.message wichtig, da dort anscheinend meine Anfrage enthalten ist. 

- Wie kann ich als Entwickler definieren, wie mein Bot aktiviert wird? Kann ich das überhaupt? Wenn nein, was muss ich beachten? 
- Gibt es eine Möglichkeit, Anfragen strukturiert geliefert zu bekommen? Ich hätte z.B. erwartet, dass wenn ich frage: _"Welche Kultur Veranstaltungen finden heute in Bonn statt?" _ dass ich irgendwo etwas abgreifen kann á la: 
```
Entities: Bonn [Location]
Time: Today [1521658389]
Keywords: Kultur Veranstaltung Bonn
```

* Da ich ein umfangreicheres API nutze: Gibt es Best-Practice und Beispiele für mehrstufige Anfragen? Beispiel: "Was geht heute Abend in Bonn?" -> "Hier ist eine Liste. Was interessiert dich" -> Nutzerinteraktion -> usw.

**Comment by knicken** [comment]
Hallo BastiTee
Zu deinen Fragen: 
* Die meisten Informationen zum Session und Message Objekt wirst du in der Documentation vom MS Boframework finden: https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html
* Die Entscheidung welcher Bot angesprochen wird, wird bei uns von einem Service wie https://dialogflow.com/ in Form eines Expertens übernommen. Nach einem Abgleich auf Intens startet dieser dann mithilfe einer "Custom payload" den nächsten Experten
* Komplexe Dialoge bilden wird mit einem Wasserfall ab. Dieser wird in folgender Dokumentation beschrieben: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-dialog-waterfall

Viele Grüße
Benedict
